name: agriculture
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  flutter_launcher_icons: ^0.11.0
  intl: ^0.18.0
  google_fonts: ^3.0.1
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  toast: ^0.3.0
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  file_picker: ^5.2.4
  collection: ^1.16.0
  

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/

